### ISSUE TITLE
Create DB 

### ISSUE THREAD

**Issue by Osttik** [19-20-1-PMi33/CourseSelector#1]
Build ar-diagram for db

**Comment by DanyloTymets** [comment]
![PI_diagram](https://user-images.githubusercontent.com/56023366/75480571-2fd4a980-59aa-11ea-8e51-6e11a4d2d108.png)

Added ER-diagram

**Comment by SchematicM** [comment]
Good job, DanyloTymets) Now it looks better than in my copybook ;)
